/**
 * The state machine for **conversation mode** — continuous talking, no
 * touching the screen.
 *
 * Ported from an earlier voice prototype. There the mic has two paths —
 * record and send to a server, or the Web Speech API — plus a whole
 * `/api/speech/info` layer to pick between them. Here **only the browser path
 * remains**: this repo's server (`server/`) has no speech-to-text route — it
 * only proxies the LLM, TTS, music search and web lookups — and web STT is the
 * path measured with a real mic on real Vietnamese. That drops both
 * `useRecorderStt` and `useSpeechInfo`, and the "no interim" branch too — the
 * web path streams words out gradually, so there is always some text to look
 * at.
 *
 * A turn has only three phases, running in a loop:
 *
 *   listen ──(end of turn)──▶ think ──(reply ready)──▶ speak ──(done)──▶ listen
 *
 * Three decisions worth writing down, because all three are trade-offs rather
 * than obvious:
 *
 * **The mic is fully off while the assistant speaks.** Speaker and mic share
 * one device; the echoed TTS voice would be recognized as a new command and
 * the car would end up ordering itself around. The price: cutting in while the
 * car is **speaking** often swallows the first word, because recognition only
 * restarts after sound is detected. While the car is **thinking** it's
 * different: the car is silent, nothing echoes back, so (with barge-in on)
 * recognition keeps running and the cut-in words are kept intact from the
 * start — "thôi không mở nữa" ("never mind, don't open it") isn't clipped to
 * "mở nữa" ("open it more").
 *
 * **The turn ends on what was said, not on a clock.** 400 ms of silence after
 * `cho tôi` ("give me…") and after `bật điều hoà đi` ("turn on the A/C") are
 * two entirely different things, and a fixed threshold can't tell them apart:
 * set it short and it cuts off people mid-thought, set it long and everyone
 * has to sit and wait while the car has already heard enough.
 * `evaluateEndpoint` reads Vietnamese sentence-final particles to decide, so a
 * complete utterance commits at ~250 ms while one left hanging gets up to
 * 1.3 s. See `endpoint.ts`.
 *
 * **What gets read aloud is `describeResult`, not the model's words.**
 * `runVoiceCommand` returns exactly the string the status bar shows; reading
 * that same string back means ear and eye never disagree. The model in this
 * repo only produces tool calls — it has no business writing spoken
 * sentences; replies are generated by code (`src/domain/say.ts`) from the
 * `ToolResult`.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

import { useConversationStore } from '@/store/conversation-store'
import { cancelVoiceCommand, runVoiceCommand } from '@/store/run-voice-command'
import { useSessionStore } from '@/store/session-store'

import { playAck } from './ack-sound'
import { evaluateEndpoint } from './endpoint'
import { useMicLevel } from './use-mic-level'
import { useSpeechQueue } from './use-speech-queue'
import { useSpeechRecognition } from './use-speech-recognition'

/**
 * Minimum gap between two calls to `evaluateEndpoint`.
 *
 * It returns `maxWaitMs = 0` on the "speech in progress" branch, so without a
 * floor `setTimeout(0)` would spin and burn CPU.
 */
const ENDPOINT_POLL_MS = 100

/**
 * If a cut-in while the car is thinking still yields no words after this many
 * ms, resend the held utterance (`carry`) on its own.
 *
 * The speech detector goes by volume, so a horn or a passenger is enough to
 * cut the turn. Without this fallback, the driver's command would be swallowed
 * by a noise nobody meant as speech.
 */
const CARRY_TIMEOUT_MS = 3000

/**
 * Barge-in while the car is **speaking** is harder than while it's thinking,
 * because the speakers are playing.
 *
 * `echoCancellation` removes the page's own audio (ElevenLabs `<audio>`) but
 * barely touches `speechSynthesis` — that voice is played by the OS and goes
 * around Chrome. At the normal threshold (0.05) the TTS voice echoing into the
 * mic is enough for the car to barge in on itself after a few words. So while
 * speaking: a higher threshold, it must stay loud longer, and the opening
 * stretch is ignored — the echo canceller needs that long to lock onto the
 * speaker audio.
 */
const SPEAKING_THRESHOLD = 0.12
const SPEAKING_SUSTAIN_MS = 350
const SPEAKING_GRACE_MS = 500

export type CallPhase = 'listening' | 'thinking' | 'speaking'

export type CallSession = {
  phase: CallPhase
  muted: boolean
  bargeIn: boolean
  /** The in-progress (interim) part of the current turn. */
  interim: string
  /** The final part of the current turn, not yet sent. */
  draft: string
  /** The utterance of the turn just sent. Empty once a new turn has started. */
  lastTurn: string
  /**
   * Whether the mic level is worth drawing — false when the mic is muted or
   * the assistant isn't listening. The number itself is read via
   * `useVoiceLevel(levelLive)`, not here: it changes every frame, and keeping
   * it in this object would make all of `App` re-render with it.
   */
  levelLive: boolean
  error: string | null
  /** Anything missing must be spelled out by the UI — don't leave users guessing. */
  supported: { recognition: boolean; voice: boolean }
  /**
   * The voice speaking — `ElevenLabs · <voice>` or the OS voice.
   *
   * There are two sound sources and they sound completely different, so "why
   * does this sentence sound like a dictation machine" must be answerable by
   * eye, not by opening DevTools to see whether `/api/tts` returned 200.
   */
  voiceName: string | null
  toggleMute: () => void
  setBargeIn: (on: boolean) => void
  /** Barge in on the assistant: stop speaking, and drop the turn still thinking. */
  interrupt: () => void
}

export type CallSessionOptions = {
  active: boolean
  /**
   * Whether the model has finished loading. The mic must not turn on before
   * then: speaking into a mic with no model behind it sends the words into the
   * void — the same reason the Start button on the dock is locked while the
   * engine isn't ready.
   */
  ready: boolean
}

export function useCallSession({
  active,
  ready,
}: CallSessionOptions): CallSession {
  const [muted, setMuted] = useState(false)
  // On by default: the toggle has left the dock, so cutting in is the driver's
  // only way to stop a long reply.
  const [bargeIn, setBargeIn] = useState(true)
  const [interim, setInterim] = useState('')
  const [draft, setDraft] = useState('')
  const [lastTurn, setLastTurn] = useState('')
  const [error, setError] = useState<string | null>(null)
  /** A turn has been sent and is waiting for its tool call to finish. */
  const [pending, setPending] = useState(false)

  const draftRef = useRef('')
  const interimRef = useRef('')
  const endpointTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  /**
   * The last time the ASR still produced words.
   *
   * This is "silence" in the only sense this hook can measure: the Web Speech
   * API doesn't report volume, only whether it still hears words. This mark is
   * enough because we only need to know how long the user has stopped *saying
   * content*.
   */
  const lastVoiceAt = useRef(0)
  /**
   * Only the "listening" phase may accept words.
   *
   * The Web Speech API still emits results a beat after being turned off.
   * Without blocking them here, that tail lands in the next turn, the silence
   * timer restarts, and the same command gets sent twice — meaning the car
   * does it twice.
   */
  const acceptingRef = useRef(false)
  /** Turn token: a turn cut off midway must not keep talking when it returns. */
  const turnSeq = useRef(0)
  /**
   * The utterance of a turn cut off **while the car was thinking**, waiting to
   * be prepended to the next turn.
   *
   * A cut-in is almost always *continuing* rather than a change of mind: "bật
   * điều hoà" ("turn on the A/C") … "ở 22 độ" ("at 22 degrees"). Sending the
   * second part alone loses the first one entirely.
   *
   * Only kept when that turn **hasn't touched the car**. The cloud path runs
   * tools mid-loop, so the cut-off turn may already have raised the
   * temperature — resending it would raise it twice. In that case
   * `cancelVoiceCommand` has already logged what was done into the history, and
   * the continuation goes out on its own, with context.
   *
   * A cut-in while the car is **speaking** keeps nothing: that turn has already
   * finished and is already in the conversation history.
   */
  const carryRef = useRef('')
  const [carry, setCarry] = useState('')
  const carryTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  /** The reply being spoken — so a barge-in knows which history turn to fix. */
  const speakingReplyRef = useRef('')
  /** `lastTurn` for handlers that run outside render (mic, timers). */
  const lastTurnRef = useRef(lastTurn)
  /** Start of the speaking phase — to ignore speaker echo at the very start. */
  const speakingSinceRef = useRef(0)
  const mutedRef = useRef(muted)

  const clearEndpointTimer = useCallback(() => {
    if (endpointTimer.current) {
      clearTimeout(endpointTimer.current)
      endpointTimer.current = null
    }
  }, [])

  const clearCarry = useCallback(() => {
    if (carryTimer.current) {
      clearTimeout(carryTimer.current)
      carryTimer.current = null
    }
    carryRef.current = ''
    setCarry('')
  }, [])

  const resetTurn = useCallback(() => {
    clearEndpointTimer()
    draftRef.current = ''
    interimRef.current = ''
    setDraft('')
    setInterim('')
  }, [clearEndpointTimer])

  const queue = useSpeechQueue()

  const phase: CallPhase = queue.speaking
    ? 'speaking'
    : pending
      ? 'thinking'
      : 'listening'

  const phaseRef = useRef(phase)

  /** Send a turn off and speak the reply. */
  const dispatchTurn = useCallback(
    async (text: string) => {
      if (!text) return

      queue.cancel()
      playAck()
      speakingReplyRef.current = ''
      setLastTurn(text)
      setPending(true)

      const myTurn = ++turnSeq.current
      const reply = await runVoiceCommand(text, 'voice')
      // Barged in on, or replaced by a later turn — that turn has set up its own
      // state, and overwriting it here would switch off someone else's lights.
      if (turnSeq.current !== myTurn) return

      setPending(false)
      if (reply) {
        speakingReplyRef.current = reply
        queue.enqueue(reply)
        // `seal` fires `onIdle` even when the machine has no vi-VN voice, so the
        // "speaking" phase never hangs — at worst it lasts exactly 0 ms.
        queue.seal()
      }
    },
    [queue],
  )

  const submitTurn = useCallback(() => {
    if (!acceptingRef.current) {
      resetTurn()
      return
    }
    const text = `${carryRef.current} ${draftRef.current} ${interimRef.current}`
      .replace(/\s+/g, ' ')
      .trim()
    resetTurn()
    clearCarry()
    // The mic may keep listening into the "thinking" phase: start a new session
    // so the tail of the utterance just sent isn't picked up as a cut-in that
    // then cuts off the very turn just sent.
    restartRecognitionRef.current()
    void dispatchTurn(text)
  }, [clearCarry, dispatchTurn, resetTurn])

  /**
   * Self-scheduling loop: ask `evaluateEndpoint`, then reschedule exactly when
   * it says to ask again. No fixed tick — a complete utterance is re-checked
   * after ~130 ms, one left hanging just sleeps until the 1.3 s ceiling.
   *
   * Goes through a `ref` because the timer function and the check function
   * reference each other.
   */
  const checkEndpointRef = useRef<() => void>(() => {})
  /** `recognition.restart` — that hook is declared after the callbacks using it. */
  const restartRecognitionRef = useRef<() => void>(() => {})
  /** `cutIn` — same reason: it's declared after the ASR handlers. */
  const cutInRef = useRef<(keepUnfinished: boolean) => void>(() => {})

  const armEndpointTimer = useCallback(
    (delayMs: number) => {
      clearEndpointTimer()
      endpointTimer.current = setTimeout(
        () => checkEndpointRef.current(),
        Math.max(delayMs, ENDPOINT_POLL_MS),
      )
    },
    [clearEndpointTimer],
  )

  const checkEndpoint = useCallback(() => {
    if (!acceptingRef.current) {
      resetTurn()
      return
    }
    const decision = evaluateEndpoint({
      stableText: draftRef.current,
      fullPartial: `${draftRef.current} ${interimRef.current}`
        .replace(/\s+/g, ' ')
        .trim(),
      silenceMs: Math.round(performance.now() - lastVoiceAt.current),
      /**
       * Deliberately always `false`, even though `useMicLevel` has RMS at hand.
       *
       * Wiring RMS in here sounds sensible but makes the system worse exactly
       * where it has to work: in a moving car, the volume never drops below
       * the threshold, and the turn would never be committed. This loop only
       * runs once the ASR has stopped producing words, so it already implies
       * silence.
       */
      localSpeechActive: false,
    })

    if (decision.decision === 'COMMIT') {
      submitTurn()
      return
    }
    armEndpointTimer(decision.maxWaitMs)
  }, [armEndpointTimer, resetTurn, submitTurn])

  /** ASR just produced words: move the silence mark to now and rearm the loop. */
  const noteVoice = useCallback(() => {
    // Words were heard, so the held utterance will go with this turn — drop
    // the send-it-alone fallback.
    if (carryTimer.current) {
      clearTimeout(carryTimer.current)
      carryTimer.current = null
    }
    lastVoiceAt.current = performance.now()
    setLastTurn('')
    armEndpointTimer(0)
  }, [armEndpointTimer])

  /**
   * Words while the car is thinking = the driver cutting in. Cut the turn right
   * away, before writing the words into the draft — don't wait for the volume
   * detector, since a quiet voice may not cross the threshold even though the
   * ASR still hears it.
   */
  const cutInIfThinking = useCallback(() => {
    if (phaseRef.current === 'thinking') cutInRef.current(true)
  }, [])

  const handleFinal = useCallback(
    (chunk: string) => {
      if (!acceptingRef.current) return
      cutInIfThinking()
      draftRef.current = `${draftRef.current} ${chunk}`
        .replace(/\s+/g, ' ')
        .trim()
      interimRef.current = ''
      setDraft(draftRef.current)
      setInterim('')
      noteVoice()
    },
    [cutInIfThinking, noteVoice],
  )

  const handleInterim = useCallback(
    (text: string) => {
      if (!acceptingRef.current) return
      if (text.trim()) cutInIfThinking()
      interimRef.current = text
      setInterim(text)
      // Still talking, so the turn isn't over — push the silence mark out.
      if (text.trim()) noteVoice()
    },
    [cutInIfThinking, noteVoice],
  )

  /**
   * `keepUnfinished` is only on when the driver **cuts in by speaking**.
   * Pressing the stop button means a real cancel; holding the utterance to send
   * later would go against what the presser wanted.
   */
  const cutIn = useCallback(
    (keepUnfinished: boolean) => {
      const wasThinking = phaseRef.current === 'thinking'
      // `lastTurn` via ref: this runs from a mic handler, not from render.
      const unfinished = lastTurnRef.current

      turnSeq.current += 1
      const progress = queue.cancel()
      const touchedCar = cancelVoiceCommand()
      setPending(false)
      // Switch phase right away, without waiting for a render: the ASR's next
      // words arrive before the next render, and must not cut the turn again.
      phaseRef.current = 'listening'
      if (wasThinking) {
        // Recognition ran through the whole thinking phase: the draft holds
        // exactly the words the driver just cut in with, and clearing it would
        // lose the start of the sentence.
        clearEndpointTimer()
      } else {
        resetTurn()
      }

      const reply = speakingReplyRef.current
      speakingReplyRef.current = ''
      if (progress && reply) {
        useConversationStore.getState().truncateReply(reply, progress.heard)
      }

      if (keepUnfinished && wasThinking && unfinished && !touchedCar) {
        if (carryTimer.current) clearTimeout(carryTimer.current)
        carryRef.current = unfinished
        setCarry(unfinished)
        carryTimer.current = setTimeout(() => {
          carryTimer.current = null
          if (
            !acceptingRef.current ||
            draftRef.current ||
            interimRef.current ||
            !carryRef.current
          )
            return
          const text = carryRef.current
          clearCarry()
          void dispatchTurn(text)
        }, CARRY_TIMEOUT_MS)
      }
    },
    [clearCarry, clearEndpointTimer, dispatchTurn, queue, resetTurn],
  )

  const interrupt = useCallback(() => cutIn(false), [cutIn])

  /**
   * Recognition also runs while the car is thinking if barge-in is on: the car
   * is silent so there's no echo, and having it already running means cut-in
   * words don't lose the first half second waiting for `start()`. While the car
   * is speaking it stays off — the TTS voice would be recognized as a command.
   */
  const recognizing =
    active &&
    ready &&
    !muted &&
    (phase === 'listening' || (phase === 'thinking' && bargeIn))

  // All the "latest value" refs are synced in exactly one place, in an effect
  // rather than during render. They're only read from timers and from Web
  // Speech API handlers — both run after paint, so being one beat late doesn't
  // change behavior.
  useEffect(() => {
    if (phase === 'speaking' && phaseRef.current !== 'speaking') {
      speakingSinceRef.current = performance.now()
    }
    mutedRef.current = muted
    phaseRef.current = phase
    checkEndpointRef.current = checkEndpoint
    cutInRef.current = cutIn
    lastTurnRef.current = lastTurn
    acceptingRef.current = recognizing
  })

  const recognition = useSpeechRecognition({
    enabled: recognizing,
    lang: 'vi-VN',
    onFinal: handleFinal,
    onInterim: handleInterim,
    onError: setError,
    onRecover: useCallback(() => setError(null), []),
    restartRef: restartRecognitionRef,
  })

  const mic = useMicLevel({
    enabled: active,
    threshold: phase === 'speaking' ? SPEAKING_THRESHOLD : undefined,
    sustainMs: phase === 'speaking' ? SPEAKING_SUSTAIN_MS : undefined,
    onSpeechStart: useCallback(() => {
      // Muted means not listening: talking to the person next to you must not
      // cancel a command.
      if (!bargeIn || mutedRef.current) return
      if (phaseRef.current === 'listening') return
      if (
        phaseRef.current === 'speaking' &&
        performance.now() - speakingSinceRef.current < SPEAKING_GRACE_MS
      ) {
        // Don't latch this burst yet: if the driver keeps talking past the
        // opening stretch, cut in then.
        return false
      }
      cutInRef.current(true)
    }, [bargeIn]),
  })

  const toggleMute = useCallback(() => {
    setMuted((on) => {
      // Muting mid-turn also discards what has been heard so far: sending half
      // a command is worse than sending nothing — half a sentence is still a
      // tool call.
      if (!on) {
        resetTurn()
        clearCarry()
      }
      return !on
    })
  }, [clearCarry, resetTurn])

  // The persona is the only thing that shows which phase the car is in without
  // reading text. `runVoiceCommand` handles its own "thinking" phase; here we
  // only set the other two, and restore the listening phase after each time
  // speaking finishes.
  useEffect(() => {
    if (!active) return
    const session = useSessionStore.getState()
    session.setMicActive(phase === 'listening' && !muted && ready)
    if (phase === 'speaking') session.setPersonaState('speaking')
    else if (phase === 'listening') {
      session.setPersonaState(muted ? 'idle' : 'listening')
    }
  }, [active, phase, muted, ready])

  // Clean everything up on hang-up — otherwise the speech queue keeps running
  // after the conversation bar has closed.
  //
  // `set-state-in-effect` is disabled on purpose: `active` is the switch of a
  // **system outside React** (mic, `speechSynthesis`, the running generation),
  // and turning it off must reset the unfinished turn's state at the same time.
  // There is no event to hook into — the switch can be flipped from elsewhere,
  // not just by the hang-up button.
  /* oxlint-disable react/set-state-in-effect */
  const wasActiveRef = useRef(active)
  useEffect(() => {
    const hungUp = wasActiveRef.current && !active
    wasActiveRef.current = active
    if (active) return
    // Hanging up mid-turn cancels it outright: a command that hasn't run must
    // not run after the driver has closed the conversation. Only right at
    // hang-up — this effect also re-runs while off, and then the running turn
    // may be a typed command.
    if (hungUp) cancelVoiceCommand()
    turnSeq.current += 1
    queue.cancel()
    resetTurn()
    clearCarry()
    speakingReplyRef.current = ''
    setLastTurn('')
    setPending(false)
    setMuted(false)
    // Clear the error on **hang-up**, not on open: clearing it after opening
    // makes the previous call's warning flash for one frame and vanish.
    setError(null)
    const session = useSessionStore.getState()
    session.setMicActive(false)
    if (!session.thinking) session.setPersonaState('idle')
  }, [active, clearCarry, queue, resetTurn])
  /* oxlint-enable react/set-state-in-effect */

  useEffect(() => clearEndpointTimer, [clearEndpointTimer])
  useEffect(
    () => () => {
      if (carryTimer.current) clearTimeout(carryTimer.current)
    },
    [],
  )

  // Keep the screen on for the whole conversation: the user is talking, not
  // touching anything, and on mobile a screen turning off takes both the mic
  // and the TTS voice down with it.
  useEffect(() => {
    if (
      !active ||
      typeof navigator === 'undefined' ||
      !('wakeLock' in navigator)
    )
      return

    let sentinel: WakeLockSentinel | null = null
    let released = false

    const request = async () => {
      try {
        sentinel = await navigator.wakeLock.request('screen')
      } catch {
        // Low battery, or the browser refused — not an error worth reporting.
      }
    }

    const onVisible = () => {
      if (!released && document.visibilityState === 'visible') void request()
    }

    void request()
    document.addEventListener('visibilitychange', onVisible)
    return () => {
      released = true
      document.removeEventListener('visibilitychange', onVisible)
      void sentinel?.release().catch(() => undefined)
    }
  }, [active])

  return useMemo(
    () => ({
      phase,
      muted,
      bargeIn,
      interim,
      // The held utterance shows at the front of the final part, so the driver
      // sees the car still remembers the first half and only has to finish it.
      draft: `${carry} ${draft}`.trim(),
      lastTurn,
      levelLive: !muted && phase === 'listening',
      error: error ?? mic.error,
      supported: { recognition: recognition.supported, voice: queue.supported },
      voiceName: queue.voiceName,
      toggleMute,
      setBargeIn,
      interrupt,
    }),
    [
      phase,
      muted,
      bargeIn,
      interim,
      carry,
      draft,
      lastTurn,
      mic.error,
      error,
      recognition.supported,
      queue.supported,
      queue.voiceName,
      toggleMute,
      interrupt,
    ],
  )
}
